/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Oct 18, 2010, 1:05:15 PM
 */

package mykmapsolver;

import java.awt.*;
import java.awt.Graphics2D;
import javax.swing.*;
import javax.swing.table.*;
import java.util.*;

public class MainFrame extends javax.swing.JFrame {

   	KMap km1, km2;
	String [] expr;
        String r, c;
    public MainFrame(String name) {
        	setTitle("K Map Solver");
		expr = new String [2];
		this.setBackground(Color.BLACK);
        initComponents();
		answer.setBackground(Color.WHITE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TruthTable = new javax.swing.JTable();
        simplify = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        conv = new javax.swing.JButton();
        answer = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        nVar = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setOpaque(false);

        TruthTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TruthTable.setOpaque(false);
        jScrollPane1.setViewportView(TruthTable);

        simplify.setText("Simplify>>");
        simplify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simplifyActionPerformed(evt);
            }
        });
        simplify.setHideActionText(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addComponent(simplify, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(simplify, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel1.setBounds(10, 230, 440, 630);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel2.setOpaque(false);

        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        conv.setText("To POS");
        conv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convActionPerformed(evt);
            }
        });

        answer.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addComponent(conv, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(conv, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2.setBounds(450, 600, 450, 270);
        jLayeredPane1.add(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel3.setOpaque(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanel3.setBounds(480, 240, 410, 360);
        jLayeredPane1.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel4.setOpaque(false);

        nVar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6", "7", "8" }));
        nVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nVarActionPerformed(evt);
            }
        });
        nVar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nVarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(nVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(nVar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel4.setBounds(10, 120, 420, 90);
        jLayeredPane1.add(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mykmapsolver/31.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBounds(0, 0, 900, 870);
        jLayeredPane1.add(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
/*
    private void nVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nVarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nVarActionPerformed
*/
    /**
    * @param args the command line arguments
    */

  private void nVarActionPerformed(java.awt.event.ActionEvent evt) {
		int n = Integer.parseInt(nVar.getSelectedItem().toString());
		Term.set_nBits(n);
		initTable(n);

                char ch = 'A';

                StringBuffer sb = new StringBuffer();
                for(int i = 0; i < n/2; i++)
                    sb.append((char)(ch++));
                r = sb.toString();

                sb = new StringBuffer();
                for(int i = 0; i < (n+1)/2; i++)
                    sb.append((char)(ch++));
                c = sb.toString();
	}

	private void simplifyActionPerformed(java.awt.event.ActionEvent evt) {
		int [][] a = getMinterms();
		km1 = new KMap(a[0], a[1]);
		PITable p = new PITable(a[0],a[1]);
		p.reduceTable();
		if(!p.isTableEmpty()) p.finish();
		expr[0] = p.expr()[0];
		expr[1] = p.expr()[1];
		answer.setText(expr[0]);
		km2 = new KMap(p.result());
		conv.setText("To POS");
		repaint();







		//String s=new String();
		int []arr=new int[1<<Term.get_nBits()];
		arr=p.checkAns();
		/*for(int i=0;i<1<<Term.get_nBits();i++){
				s=s+" "+arr[i];
			}
		JOptionPane.showMessageDialog( null, "The sum is " + s, "Results", JOptionPane.PLAIN_MESSAGE );
*/
         for(int i=0;i<(1<<Term.get_nBits());i++)
              TruthTable.setValueAt(arr[i], i,Term.get_nBits()+2 );

         boolean f=true;
         for(int i = 0; i < TruthTable.getRowCount(); i++)
		{
			if((TruthTable.getValueAt(i, TruthTable.getColumnCount()-2)).toString().equals("1")&& (arr[i]!=1)){
							f=false;
							break;

				}
			else if((TruthTable.getValueAt(i, TruthTable.getColumnCount()-2)).toString().equals("0")&& (arr[i]!=0)){
							f=false;
							break;

				}

		}

		/*if(f)
			JOptionPane.showMessageDialog( null, "Answer is correct", "Results", JOptionPane.PLAIN_MESSAGE );
		else
			JOptionPane.showMessageDialog( null, "Answer is not correct", "Results", JOptionPane.PLAIN_MESSAGE );
                    */
         if(f)
             jTextField1.setText("Correct!");
         else
             jTextField1.setText("Not Correct!");





}

private void convActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
	if(conv.getText().equals("To SOP"))
	{
		conv.setText("To POS");
		answer.setText(expr[0]);
	}
	else
	{
		conv.setText("To SOP");
		answer.setText(expr[1]);
	}
}

	void initTable(final int n)
	{
		Integer [][] array = new Integer [1 << n][n+3];
		for(int i = 0; i < (1 << n); i++)
		{
			array[i][0] = i;
			for(int j = n; j >= 1; j--)
				array [i][j] = ((i & (1 << (n-j))) != 0) ? 1 : 0;
			array[i][n+1] = 0;
		}

		String [] header = new String [n+3];
        header[0] = "Minterm";
		for(int i = 1; i <= n; i++)
			header[i] = new StringBuffer(0).append((char)('A'+i-1)).toString();
		header[n+1] = "Output";
		header[n+2] = "check";

        TruthTable.setModel(new javax.swing.table.DefaultTableModel(
            array, header)
		{
			public boolean isCellEditable(int i, int j)
			{
				return (j == n+1) ? true : false;
			}
		});




             /*   Integer [][] array1=new Integer [1 << n][1];
                String [] header1=new String [1];
                header1[0]="check";
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
            array1, header1)
		{
		public boolean isCellEditable(int i, int j)
			{
				return true ;
			}
		});*/

		// for selecting one row at a time
		TruthTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

		// for center text alignment in the cells
	/*	DefaultTableCellRenderer LARenderer = new LeftAlignRenderer();
		for(int i = 0; i < n+2; i++)
			TruthTable.getColumnModel().getColumn(i).setCellRenderer(LARenderer);*/

		// for the comboboxes in the output column
		DefaultTableModel model = (DefaultTableModel)TruthTable.getModel();
		String[] values = new String[]{"0", "1", "x"};
		int vColIndex = TruthTable.getColumnCount()-2;
		TableColumn col = TruthTable.getColumnModel().getColumn(vColIndex);
		col.setCellEditor(new MyComboBoxEditor(values));
	}

	int [][] getMinterms()
	{
		ArrayList <Integer> min = new ArrayList<Integer>();
		ArrayList <Integer> dont = new ArrayList<Integer>();
		for(int i = 0; i < TruthTable.getRowCount(); i++)
		{
			if((TruthTable.getValueAt(i, TruthTable.getColumnCount()-2)).toString().equals("1"))
				min.add(i);
			else if((TruthTable.getValueAt(i, TruthTable.getColumnCount()-2)).toString().equals("x"))
					dont.add(i);
		}
		int [][] a = new int [2][];
		a[0] = new int [min.size()];
		for(int i = 0; i < min.size(); i++)
			a[0][i] = min.get(i);
		a[1] = new int [dont.size()];
		for(int i = 0; i < dont.size(); i++)
			a[1][i] = dont.get(i);
		return a;
	}
	public void paint (java.awt.Graphics g)
	{
		int originX, originY, lim, length, height, cellSize;
		Graphics2D g2 = (Graphics2D) g;

		length = height = 360;
		originX = 480;
		originY = 270;
		lim = length/2;
		cellSize = 20;

		super.paint (g);
		g2.setColor(Color.WHITE);
                g2.fillRect(originX-5, originY-5, length+10, height+10);

		g2.setColor(Color.BLACK);

		int col = km1.getMap()[0].length;
		int row = km1.getMap().length;

		int X = originX+(length-(2+col)*cellSize)/2;
		int Y = originY+(height-(2+row)*cellSize)/2;

		g2.drawRect(X, Y, (2+col)*cellSize, (2+row)*cellSize);
		g2.setColor(Color.LIGHT_GRAY);
		g2.fillRect(X, Y, (2+col)*cellSize, 2*cellSize);
		g2.fillRect(X, Y, 2*cellSize, (2+row)*cellSize);

		for(int i = 0; i < km1.getMap().length; i++)
			g2.drawLine(X, Y+cellSize*(i+2), X+(2+col)*cellSize, Y+cellSize*(i+2));
		for(int i = 0; i < km1.getMap()[0].length; i++)
			g2.drawLine(X+cellSize*(i+2), Y, X+cellSize*(i+2), Y+(2+row)*cellSize);

		for(int i = 0; i < row; i++)
		{
			for(int j = 0; j < col; j++)
			{
				Character c = km1.getMap()[i][j];
				if(c == '1') g2.setColor(new Color(192, 0, 0));
				else if(c == 'x') g2.setColor(new Color(0, 0, 192));
				else g2.setColor(new Color(0, 200, 0));
				g2.drawString(c.toString(), X+cellSize*(j+2)+5, Y+cellSize*(i+3)-5);
			}
		}

                g2.setColor(Color.RED);
                g2.drawString(r, X+2, Y+2*cellSize+4);
		g2.setColor(Color.BLACK);
		for(int i = 0; i < row; i++)
			g2.drawString(km1.getRowHead()[i], X+5, Y+(3+i)*cellSize-3);

		g2.translate(X, Y+2*cellSize);
		g2.rotate(-Math.PI/2.0);
                g2.setColor(Color.RED);
                g2.drawString(c, 3, 2*cellSize+4);
		g2.setColor(Color.BLACK);
		for(int i = 0; i < col; i++)
			g2.drawString(km1.getColHead()[i], 3, (3+i)*cellSize-2);
	}

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
				try
				{
					javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
				} catch (Exception ex)
				{
				}
                new MainFrame("K Map Solver").setVisible(true);
            }
        });
    }	

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TruthTable;
    private javax.swing.JTextField answer;
    private javax.swing.JButton conv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox nVar;
    private javax.swing.JButton simplify;
    // End of variables declaration//GEN-END:variables

}
